### PR TITLE
removeTags & addTags functions added.

### PR DESCRIPTION
**Pull request by meminuygur**
fixes [#41](https://github.com/spatie/mailcoach-sdk-php/issues/41)

### CODE REVIEW

**Comment by freekmurze** [comment]
Could you also update the readme?

**Comment by meminuygur** [comment]
> Could you also update the readme?

Will do

**Comment by meminuygur** [comment]
@freekmurze could you check the updated PR please ?

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
